texasholdemcomponent:
  matchingSuit: true
  opponentCount: 1
  handCount: 100000

texasholdemmain:
  loopCount: 3

app:
  execution-time:
    output-dir: src/main/docs/optimisationrecord
    file-prefix: execution_time
    date-format: yyyyMMdd_HHmmss
    time-format: yyyy-MM-dd HH:mm:ss.SSS